# Generated by Django 2.2 on 2019-04-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_steg', '0002_auto_20190418_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stegimage',
            field=models.ImageField(default='default.jpeg', upload_to='steg_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='stegtext',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='hiddentext',
            field=models.TextField(max_length=60),
        ),
    ]
